New feature: dataset custom schema
datopian/ckanext-honduras pull request #36
Opened 2019-07-02 14:22 UTC by borism

As per https://docs.google.com/spreadsheets/d/1D2UyTfHANXO5jO_RkBj5d6de5prkrpSe3KgYolBwTyk/edit#gid=1697736576

2019-07-04 09:10 UTC, amercader requested changes
Nice work @borism , I added some comments to make it more aligned with the standard CKAN schema

2019-07-04 09:10 UTC, amercader commented on ckanext/honduras/dataset.json
> +      "field_name": "description",
Use `notes` here, as this is the default CKAN field for this

2019-07-04 09:10 UTC, amercader commented on ckanext/honduras/dataset.json
> +      "required": true
this should be a [`select` preset](https://github.com/ckan/ckanext-scheming/#choices). The `choices` are in the "VARIABLES" sheet of the spreadsheet (Column "Categoría de Información"). Use the values on the spreadsheet as labels, and for values the lower-case, hyphenated form of them (also replacing accents like í -> i)

2019-07-04 09:10 UTC, amercader commented on ckanext/honduras/dataset.json
> +      "field_name": "keyword",
Use the core `tags` field for this, as described [here](https://github.com/ckan/ckanext-scheming/blob/master/ckanext/scheming/ckan_dataset.json#L25) but changing the label.

2019-07-04 09:10 UTC, amercader commented on ckanext/honduras/dataset.json
> +      "label": "Fecha de Creación del Dataset"
Use the `date` preset here

2019-07-04 09:10 UTC, amercader commented on ckanext/honduras/dataset.json
> +      "field_name": "modified",
Use the `date` preset here

2019-07-04 09:10 UTC, amercader commented on ckanext/honduras/dataset.json
> +      "field_name": "accrualPeriodicity",
this should be a [`select` preset](https://github.com/ckan/ckanext-scheming/#choices). The `choices` are in the "VARIABLES" sheet of the spreadsheet (Column "Frecuencia de actualización de la información"). Use the values on the spreadsheet as labels, and for values the lower-case, hyphenated form of them (also replacing accents like í -> i)

2019-07-04 09:10 UTC, amercader commented on ckanext/honduras/dataset.json
> +      "field_name": "license",
Copy [this field](https://github.com/ckan/ckanext-scheming/blob/master/ckanext/scheming/ckan_dataset.json#L32) definition

2019-07-04 09:10 UTC, amercader commented on ckanext/honduras/dataset.json
> +      "field_name": "decription",
typo `description`

2019-07-04 09:10 UTC, amercader commented on ckanext/honduras/dataset.json
> +      "field_name": "mediaType",
Let's use the [default `format`](https://github.com/ckan/ckanext-scheming/blob/master/ckanext/scheming/ckan_dataset.json#L101) one here

2019-07-04 09:10 UTC, amercader commented on ckanext/honduras/dataset.json
> +      "field_name": "accessURL",
Can you replace `accessURL` and `downloadURL` with the [standard `url` one](https://github.com/ckan/ckanext-scheming/blob/master/ckanext/scheming/ckan_dataset.json#L86) and move it to the top of the resource fields?

2019-07-07 23:10 UTC, sivang commented
hey, I saw this update and was wondering, shouldn't schema files be placed under a `ckanext/honduras/schema/` if one uses `ckanext-scheming` which I assume you do here or perhaps this is not critical?

2019-07-08 08:27 UTC, borism commented
> hey, I saw this update and was wondering, shouldn't schema files be placed under a `ckanext/honduras/schema/` if one uses `ckanext-scheming` which I assume you do here or perhaps this is not critical?

it works like this when I add `scheming.dataset_schemas = ckanext.honduras:dataset.json` to ckan config. perhaps there's a better place for storing this, I'm open to suggestions.

2019-07-10 09:27 UTC, merged

2019-07-10 09:28 UTC, amercader commented
Great work @borism. I added some final tweaks on 941aa86 directly so you can focus on the importer.

2019-07-10 09:30 UTC, amercader commented
@sivang You can put the json schemas wherever you want in the extension as long as you reference it correctly in the config option.. /schemas/ is more of a convention when there's more than one.